INSERT INTO formation (region_id, formation)
VALUES
(1, 'Corozal Police'),
(1, 'Orange Walk Police'),
(2, 'Police Headquarters'),
(2, 'Precinct 1'),
(2, 'Precinct 2'),
(2, 'Precinct 3'),
(2, 'Precinct 4'),
(2, 'Ladyville Police Sub-Formation'),
(2, 'Hattieville Police Sub-Formation'),
(2, 'Caye Caulker Police'),
(2, 'San Pedro Police'),
(3, 'Police Headquarters - Belmopan'),
(3, 'San Ignacio Police'),
(3, 'Benque Viejo Police'),
(3, 'Belmopan Police'),
(3, 'Roaring Creek Police Sub-Formation'),
(4, 'Punta Gorda Police'),
(4, 'Intermediate Southern'),
(4, 'Placencia Police Sub-Formation'),
(4, 'Seine Bight Police Sub-Formation'),
(4, 'Hopkins Police Sub-Formation'),
(4, 'Dangriga Police');
